# Generated by Django 5.2.5 on 2025-08-25 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detailview', '0005_place_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyWaitState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='상태 버전')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='최종 업데이트')),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wait_state', to='detailview.party', verbose_name='파티')),
            ],
        ),
    ]
