# Generated by Django 5.2.5 on 2025-08-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detailview", "0003_merge_20250818_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="places/"),
        ),
    ]
