# Generated by Django 5.2.5 on 2025-08-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detailview", "0004_alter_place_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="map",
            field=models.ImageField(blank=True, null=True, upload_to="maps/"),
        ),
    ]
