# Generated by Django 5.2.5 on 2025-08-25 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailview', '0005_place_map'),
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='상태 버전')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='최종 업데이트')),
            ],
        ),
        migrations.AlterModelOptions(
            name='balancequestion',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='balanceround',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='balancequestion',
            name='uniq_round_order',
        ),
        migrations.RemoveConstraint(
            model_name='balancevote',
            name='uniq_vote_per_user_question',
        ),
        migrations.RemoveIndex(
            model_name='balancequestion',
            name='game_balanc_round_i_f8fc4d_idx',
        ),
        migrations.RemoveIndex(
            model_name='balanceround',
            name='game_balanc_created_7d4cb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='balancevote',
            name='game_balanc_user_id_0ba8d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='balancevote',
            name='game_balanc_questio_f78f38_idx',
        ),
        migrations.RemoveField(
            model_name='balanceround',
            name='safety_blocked',
        ),
        migrations.RemoveField(
            model_name='balanceround',
            name='safety_reason',
        ),
        migrations.AlterField(
            model_name='balancequestion',
            name='vote_a_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balancequestion',
            name='vote_b_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balanceround',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_round', to='detailview.party', verbose_name='파티'),
        ),
        migrations.AlterUniqueTogether(
            name='balancequestion',
            unique_together={('round', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='balancevote',
            unique_together={('question', 'user')},
        ),
        migrations.AddField(
            model_name='roundstate',
            name='round',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='game.balanceround', verbose_name='라운드'),
        ),
    ]
