# Generated by Django 5.2.5 on 2025-08-25 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_points'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='social_id',
            field=models.CharField(db_index=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['provider', 'social_id'], name='users_socia_provide_9cf291_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['user'], name='users_socia_user_id_94573d_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'social_id'), name='uniq_provider_social'),
        ),
    ]
